### ISSUE TITLE
Can you please help me with the npm server issue?

### ISSUE THREAD

**Issue by sowmyadvn** [jvkrishna/Image-Annotation-Tool#2]
I am trying to use this annotation tool to train my model. I have followed the installation steps and having issues with starting the server in the final step. Am I missing something?  

![image](https://user-images.githubusercontent.com/22230078/30398259-9dfbc4b4-9884-11e7-96d1-d0fadc3b554e.png)

Thanks in advance,
Sowmya

**Comment by jvkrishna** [comment]
We have fixed the issue with the unused imports.  Also, Please read the latest README file for more details on the setup.

**Comment by sowmyadvn** [comment]
Thank you for really quick response. Highly appreciate it!
